spring:
  application:
    name: spring-ai
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max-latest
          temperature: 0.8 #????????????????
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.itheima.ai : debug